export const GET_ERRORS = 'GET_ERRORS';
export const USER_LOADING = 'USER_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_TICKETS = 'GET_TICKETS';
export const ADD_TICKET = 'ADD_TICKET';
export const UPDATE_TICKET = 'UPDATE_TICKET';
export const TICKETS_LOADING = 'TICKETS_LOADING';
export const ADD_COMMENT = 'ADD_COMMENT';