export const GET_ERRORS = 'GET_ERRORS';
export const USER_LOADING = 'USER_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_TICKETS = 'GET_TICKETS';
export const ADD_TICKET = 'ADD_TICKETS';
export const CLOSE_TICKET = 'CLOSE_TICKET';
export const TICKETS_LOADING = 'TICKETS_LOADING'